#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_SATSUKI,
    SP_NAME_KIO,
    SP_NAME_COUNT
};

enum BoxFrames {
    BOX_FRAME_ONE,
    BOX_FRAME_TWO,
    BOX_FRAME_THREE,
    BOX_FRAME_FOUR,
    BOX_FRAME_FIVE,
    BOX_FRAME_SIX,
    BOX_FRAME_SEVEN,
    BOX_FRAME_EIGHT,
    BOX_FRAME_NINE,
    BOX_FRAME_TEN,
    BOX_FRAME_ELEVEN,
    BOX_FRAME_TWELVE,
    BOX_FRAME_PC,
    BOX_FRAME_FOURTEEN,
    BOX_FRAME_FIFTEEN,
    BOX_FRAME_SIXTEEN,
    BOX_FRAME_SEVENTEEN,
    BOX_FRAME_EIGHTEEN,
    BOX_FRAME_BODHAI,
    BOX_FRAME_TIANA,
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
