#ifndef GUARD_TARC_BOOK_CONSTANTS_H
#define GUARD_TARC_BOOK_CONSTANTS_H

enum BookPages
{
    PAGE_NONE,
    PAGE_TEST,
    PAGE_TEST2,
    PAGE_XERNEAS_UNFINISHED_1,
    PAGE_XERNEAS_UNFINISHED_2,
    PAGE_XERNEAS_FALSE_1,
    PAGE_XERNEAS_TRUE_1,
    PAGE_XERNEAS_TRUE_2,
    PAGE_XERNEAS_TRUE_3,
    PAGE_LUGIA_UNFINISHED,
    PAGE_LUGIA_FALSE_1,
    PAGE_LUGIA_FALSE_2,
    PAGE_LUGIA_FALSE_3,
    PAGE_LUGIA_TRUE_1,
    PAGE_LUGIA_TRUE_2,
    PAGE_LUGIA_TRUE_3,
    PAGE_LUGIA_TRUE_4,
    PAGE_GIRATINA_UNFINISHED_1,
    PAGE_GIRATINA_UNFINISHED_2,
    PAGE_GIRATINA_FALSE_1,
    PAGE_GIRATINA_FALSE_2,
    PAGE_GIRATINA_TRUE_1,
    PAGE_GIRATINA_TRUE_2,
    PAGE_GIRATINA_TRUE_3,
    PAGE_COUNT
};

enum BookSpriteType
{
    SPRITE_TYPE_NONE,
    SPRITE_TYPE_MON,
    SPRITE_TYPE_DIRECT,
};

#endif
