#ifndef GUARD_TARC_BALANCE_CONSTANTS_H
#define GUARD_TARC_BALANCE_CONSTANTS_H

#define TARC_STATUS_CURE_TURN  5
#define TARC_STAT_RESTORE_TURN 3
#define TARC_HP_RESTORE_FRAC   24
#define TARC_THUNDERSTRIKE_FRACTION 16
#define TARC_FLAMES_EMBRACE_FRACTION 16
#define TARC_HAILSTONE_FALL_FRACTION 32

#endif
