#ifndef GUARD_TARC_BALANCE_CONSTANTS_H
#define GUARD_TARC_BALANCE_CONSTANTS_H

#define BOSS_LEVEL 100
#define TARC_STATUS_CURE_TURN  5
#define TARC_STAT_RESTORE_TURN 3
#define TARC_HP_RESTORE_FRAC   24
#define TARC_THUNDERSTRIKE_FRACTION 16
#define TARC_FLAMES_EMBRACE_FRACTION 16
#define TARC_HAILSTONE_FALL_FRACTION 32
#define TARC_OVERRIDE_EXHAUSTION_FRACTION 16
#define TARC_EMPATH_HP_FRACTION 24
#define TARC_TERRAS_BLESSING_HP_FRACTION 8
#define TARC_BRUTE_FORCE_MODIFIER 1.3
#define TARC_GIANT_SLAYER_STAGE_BOOST 1
#define TARC_PRECISION_POINT_STAGE_BOOST 1
#define TARC_RESORPTION_FRACTION 4
#define TARC_ROYAL_GUARD_DEF_BONUS 1.5

#define TARC_UPDRAFT_DURATION 2
#define TARC_UNCONTAINED_BLAZE_DAMAGE_FRACTION 4
#define TARC_PHALANX_REDUCTION 0.8

#define TARC_INTIMIDATE_CD 4
#define TARC_DISHEARTEN_CD 4
#define TARC_SENTINEL_CD 4
#define TARC_STATIC_BUILDUP_CD 2

#define TARC_DAMAGE_DIVISION 200

#endif
