name: General Bug Report
description: File a bug report related to battle mechanic, be it moves, abilities and/or items.
labels: ["bug", "status: unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all fields with as many details as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What behavior are you expecting to happen? What behavior are you observing instead?
      placeholder: |
        Please be as descriptive as possible.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        What exact steps can somebody else follow in order to recreate the issue on their own?
      placeholder: |
        Provide as much context as possible as to what was done to create the issue.
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Images / Video
      description: |
        Do you have images or videos to show the problem happen?
      placeholder: |
        Here you can also attach logs, screenshots, gifs or a video.
        Attach a screenshot demonstrating the problem with the Debug Info enabled.
    validations:
      required: false
