#ifndef GUARD_TARC_AI
#define GUARD_TARC_AI

#include "global.h"

enum AiMoveLists
{
    AI_LIST_ARTICUNO_1,
    AI_LIST_ARTICUNO_2,
    AI_LIST_ARTICUNO_3,
    AI_LIST_ARTICUNO_4,
    AI_LIST_ZAPDOS_1,
    AI_LIST_ZAPDOS_2,
    AI_LIST_ZAPDOS_3,
    AI_LIST_ZAPDOS_4,
    AI_LIST_MOLTRES_1,
    AI_LIST_MOLTRES_2,
    AI_LIST_MOLTRES_3,
    AI_LIST_MOLTRES_4,
};

enum Bosses
{
    BOSS_ARTICUNO,
    BOSS_ZAPDOS,
    BOSS_MOLTRES,
    BOSS_RAIKOU,
    BOSS_ENTEI,
    BOSS_SUICUNE,
    BOSS_REGIROCK,
    BOSS_REGICE,
    BOSS_REGISTEEL,
    BOSS_REGIELEKI,
    BOSS_REGIDRAGO,
    BOSS_UXIE,
    BOSS_MESPRIT,
    BOSS_AZELF,
    BOSS_COBALION,
    BOSS_TERRAKION,
    BOSS_VIRIZION,
    BOSS_KELDEO,
    BOSS_TORNADUS_THERIAN,
    BOSS_THUNDURUS_THERIAN,
    BOSS_LANDORUS_THERIAN,
    BOSS_ENAMORUS_THERIAN,
    BOSS_TAPU_KOKO,
    BOSS_TAPU_LELE,
    BOSS_TAPU_BULU,
    BOSS_TAPU_FINI,
    BOSS_WO_CHIEN,
    BOSS_CHIEN_PAO,
    BOSS_TING_LU,
    BOSS_CHI_YU,
    BOSS_OKIDOGI,
    BOSS_MUNKIDORI,
    BOSS_FEZANDIPITI,
    BOSS_ARTICUNO_GALAR,
    BOSS_ZAPDOS_GALAR,
    BOSS_MOLTRES_GALAR,
    BOSS_WALKING_WAKE,
    BOSS_GOUGING_FIRE,
    BOSS_RAGING_BOLT,
    BOSS_IRON_LEAVES,
    BOSS_IRON_BOULDER,
    BOSS_IRON_CROWN,
    BOSS_DRAGONITE,
    BOSS_TYRANITAR,
    BOSS_METAGROSS,
    BOSS_SALAMENCE,
    BOSS_GARCHOMP,
    BOSS_HYDREIGON,
    BOSS_GOODRA,
    BOSS_KOMMO_O,
    BOSS_DRAGAPULT,
    BOSS_BAXCALIBUR,
};

struct BossMoveList
{
    u32 numMoves;
    u16 moves[];
};

struct BossAi
{
    const struct BossMoveList *phaseMoves[6];
};

void SetNextBossMove(void);
void ResetTurnCounter(void);
void SetBossInBattle(void);

#endif
